version: "3.8"

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - bridge-network

  db:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bridge-network

  redis:
    image: redis:6.2.5
    command: redis-server
    networks:
      - bridge-network

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
    working_dir: /home/app/html
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      REDIS_HOST: redis
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      PORT: 3000
    command: /bin/sh ".dockerdev/commander/commander.dev.sh"
    volumes:
      - .:/home/app/html:rw
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - bridge-network

  sidekiq:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
    working_dir: /home/app/html
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      REDIS_HOST: redis
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      PORT: 3000
    command: /bin/sh -c "bundle check || bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - .:/home/app/html
      - bundle_cache:/bundle
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - bridge-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    restart: always
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  db:
  esdata:
  bundle_cache:
